[package]
name = "piccali-cli"
version = "0.6.0"
edition = "2024"
description = "A Rust CLI tool that parses Gherkin files and outputs structured data (JSON, MARKDOWN, HTML)"
repository = "https://github.com/Odonno/piccali-cli"
readme = "README.md"
license-file = "LICENSE"
keywords = ["cli", "gherkin", "cucumber"]
categories = ["command-line-utilities"]

[dependencies]
chrono = "0.4"
clap = { version = "4.6.0", features = ["derive"] }
color-eyre = { version = "0.6", default-features = false }
gherkin = { version = "0.15", features = ["parser"] }
globset = "0.4"
regex = "1"
rust-embed = { version = "8", features = ["mime-guess"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiny_http = "0.12"
url-escape = "0.1.1"
walkdir = "2"

[dev-dependencies]
assert_cmd = "2"
insta = { version = "1", features = ["json"] }
predicates = "3"
tempfile = "3"
